[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python manage.py migrate && gunicorn itaku_backend.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

