[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python manage.py migrate && python manage.py ensure_test_users && gunicorn itaku_backend.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

